### ISSUE TITLE
Investigate potential performance improvements by turning main functions to be column-wise

### ISSUE THREAD

**Issue by karoliskoncevicius** [karoliskoncevicius/matrixTests#3]
Right now all functions work on rows by default and column versions transpose the input data and call the corresponding row function.

However in R column-wise functions should be about 2x faster due to how the matrices are stored in memory. Therefore it's worth investigating if making the test functions work on columns instead of rows could add additional boost to performance.

**Comment by KKPMW** [comment]
Verdict: It's better to have separate row_ and col_ functions because:

1. Transpose can take a long time
2. Warnings and errors have to be adapted to row_ and col_ separately
3. Functions in matrixStats have no speed differences between row and col functions.
