### ISSUE TITLE
Simplify and automate unit testing

### ISSUE THREAD

**Issue by karoliskoncevicius** [karoliskoncevicius/matrixTests#7]
- [x] Remove `testthat` dependency
- [ ] ~Try to automate the parameter testing based on input argument types~

**Comment by KKPMW** [comment]
Automatic parameter testing is abandoned (for now). There are too many special cases to have a unified interface for most tests.

Might revisit in the future.

**Comment by karoliskoncevicius** [comment]
Implemented in the current dev under the following commit: https://github.com/karoliskoncevicius/matrixTests/commit/db0e1feee4642bcad55315c11a59fa2905803d9c
