### ISSUE TITLE
Make row_ievora self-contained

### ISSUE THREAD

**Issue by karoliskoncevicius** [karoliskoncevicius/matrixTests#9]
Currently `row_ievora` calls `row_bartlett` and `row_t_welch`. Both these functions do some preprocessing on their own.

Rewriting `row_ievora` to have all the needed code to run the tests within itself would improve the speeed and handling of warnings.

**Comment by KKPMW** [comment]
After some reflection I decided to remove iEvora from matrixTests entirely. Strictly speaking it doesn't behave like a statistical test and hence doesn't belong in this package.

Users can perform iEvora by applying Bartlett's test followed by Student's t-test and choosing their p-value cut-offs manually.
